version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: aiconsultant_backend
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    volumes:
      - ./backend:/app
      - files:/app/files/
    ports:
      - "8000:8000"
    networks:
      - aiconsultant_network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: development
    container_name: aiconsultant_frontend
    volumes:
      - ./frontend:/app
      - node_modules:/app/node_modules
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:8000
      - NODE_ENV=development
    depends_on:
      - backend
    networks:
      - aiconsultant_network
    stdin_open: true
    tty: true

volumes:
  files:
  node_modules:

networks:
  aiconsultant_network:
    driver: bridge
